version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

archives:
  - ids:
      - es
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    files:
      - README.md
      - LICENSE*

builds:
  - binary: es
    id: es
    ldflags:
      - -s
      - -w
      - -X github.com/zmoog/es/es/commands.version={{.Version}}
      - -X github.com/zmoog/es/es/commands.commit={{.Commit}}
      - -X github.com/zmoog/es/es/commands.date={{.Date}}
      - -X github.com/zmoog/es/es/commands.builtBy=goreleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: .

release:
  name_template: "{{.ProjectName}} v{{.Version}}"
  draft: false
  prerelease: auto

homebrew_casks:
  - name: es
    repository:
      owner: zmoog
      name: homebrew
      branch: main
    binaries:
      - es
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/es"]
          end

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
